title: Nguyen Nhat Mai # your name (or website title) here
logo: "Face image.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently pursuing Master of data science and business analytics at ESSEC & CentraleSupélec. I have a strong passion for applied data science.
  <br><br>
  <a href="https://www.linkedin.com/in/nguyen-nhatmai/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
