title: Nguyen Nhat Mai # your name (or website title) here
logo: "Face image.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A student pursuing Master of data science and business analytics at ESSEC & CentraleSupélec
  <br><br>
  A person with strong passion for improving business performance via data analytics
  <br><br>
  <a href="https://www.linkedin.com/in/nguyen-nhatmai/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
